### ISSUE TITLE
Student percentage prediction model

### ISSUE THREAD

**Issue by Rishita11** [ZeusCodes-Official/DS-Olympus-#1]
I have two ideas to work on under this domain.
1)Colour Identification in images
2) Prediction model for predicting the number of students based on the number of their study hours.

Please assign me this issue under DevIncept.

**Comment by utkarshxy** [comment]
Hey! I can see one is deep learning and the other is machine learning. Make sure you make different pull requests for both. Thanks! 
Assigning this to you.

**Comment by utkarshxy** [comment]
^ that was due to wrong linking of issue. 

@Rishita11 you are still working on both of them right ...?  You will have to create another issue for your deep learning problem.

**Comment by Rishita11** [comment]
Okay, I will create different issues for both of them.
