### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by payaldutta** [ZeusCodes-Official/DS-Olympus-#10]
I want to add the Contributors Section in the readme to showcase all the valuable contributors of this repository.
@utkarshxy Do assign me this under DCP'21.
Thank You.

**Comment by utkarshxy** [comment]
Sure go ahead! Make sure it's all the contributors. Will it be automated? Or do you have to update it manually everytime?

**Comment by payaldutta** [comment]
@utkarshxy It will be automated every time by itself.

**Comment by utkarshxy** [comment]
Amazing! Make sure you keep the original format as it is for the readme and make the changes you want at the end of it.
