### ISSUE TITLE
Want to contribute Anime and Cartoon Image classifier model to this Repo

### ISSUE THREAD

**Issue by kanakmi** [ZeusCodes-Official/DS-Olympus-#15]
- [ ] Devincept
- [ ] Mentor
- [ ] Deep Learning

I've made an Anime and Cartoon image classifier using CNN that I want to contribute to this repository. The project also features a simple UI and is deployed on Heroku. Please Assign it to me.

**Comment by utkarshxy** [comment]
Make sure your folder is in camelCase and you follow the guidelines.
