### ISSUE TITLE
Amazon Alexa Reviews Analysis (NLP)

### ISSUE THREAD

**Issue by Manasi2001** [ZeusCodes-Official/DS-Olympus-#18]
## Aim

The aim is to perform NLP and categorize the feedback given to Alexa as positive or negative.

I'm a DCP participant, please assign the issue to me.

PS: It will be added to the machineLearning folder.

**Comment by utkarshxy** [comment]
Done! Make sure you follow the guidelines and camelCase for creating your folder.
