### ISSUE TITLE
Adding CODE-OF-CONDUCT.md

### ISSUE THREAD

**Issue by Sitanshu-AI** [ZeusCodes-Official/DS-Olympus-#2]
creating a code of conduct file .

**Comment by utkarshxy** [comment]
Thanks! Sure go ahead.

**Comment by swathi-469** [comment]
I can work on this issue I am ready with the file

**Comment by utkarshxy** [comment]
Hey! @swathi-469, @Sitanshu-AI raised the issue first..so he will be doing it. If at he is not active. I will assign this to you. 
There literally 100 other ways you can contribute to this. Raise another issue. 
All the best!

**Comment by Sitanshu-AI** [comment]
i have already created a pulldown request

**Comment by utkarshxy** [comment]
Where buddy? There are no pull requests yet.

**Comment by swathi-469** [comment]
Yeah ok mam

**Comment by Sitanshu-AI** [comment]
let me check sir

**Comment by swathi-469** [comment]
Ok mam if there is he is not active I will work on it .

**Comment by Sitanshu-AI** [comment]
Please Stop calling him mam , couldn't you see he is boy

**Comment by swathi-469** [comment]
Okay I. Sorry for that . Please forgive

**Comment by utkarshxy** [comment]
It's not a problem folks! Now my profile picture should solve the problem.
