### ISSUE TITLE
Churn Risk Score Prediction (ML)

### ISSUE THREAD

**Issue by Manasi2001** [ZeusCodes-Official/DS-Olympus-#23]
## **Aim**

The aim is to predict the churn score for a website based on the features provided in the dataset.

## **ML Algorithm to be Used**

Decision Tree Classifier

## **Software to be Used for GUI**

tkinter

**Comment by harshita9621** [comment]
Can I work on this issue

**Comment by utkarshxy** [comment]
@harshita9621, Unlike many other projects, you can raise issues, anything at all and work on it. So raise the issue I will assign it to you.
