### ISSUE TITLE
Concrete Strength Prediction (ML)

### ISSUE THREAD

**Issue by Manasi2001** [ZeusCodes-Official/DS-Olympus-#24]
## Content

The feature set includes:

Cement,
Blast Furnace Slag,
Fly Ash,
Water,
Super-plasticizer,
Coarse Aggregate,
Fine Aggregate and
Age

The target set is:

Strength of the Cement

## ML Algorithm to be Used

Linear Regression

## Package to be Used for GUI

tkinter

**Comment by utkarshxy** [comment]
@Manasi2001 I've assigned it to you! Go ahead! Make sure you follow the guidelines!
