### ISSUE TITLE
Coffee Production Prediction

### ISSUE THREAD

**Issue by Akash20x** [ZeusCodes-Official/DS-Olympus-#26]
I want to add model of Coffee Production Prediction to predict average coffee production from 1990-2018. I will use different models like linear regression, Decision Tree, Random forest, Support Vector Classifier and more and compare their accuracy, RMSE and R2 score.

I will use ICO Coffee Dataset (Worldwide) kaggle dataset for my analysis and predictions. 

Dataset Link :

https://www.kaggle.com/yamaerenay/ico-coffee-dataset-worldwide

Please assign me this issue as a part of DevIncept.

**Comment by utkarshxy** [comment]
@Akash20x Go ahead!
