### ISSUE TITLE
Diabetes Prediction with ML Models

### ISSUE THREAD

**Issue by harshita9621** [ZeusCodes-Official/DS-Olympus-#28]
### Predict the onset of diabetes based on diagnostic measures

- The datasets consists of several medical predictor variables and one target variable, Outcome. Predictor variables includes the number of pregnancies the patient has had, their BMI, insulin level, age, and so on.

**Dataset**

[https://www.kaggle.com/uciml/pima-indians-diabetes-database](url)

Assign me this issue under DevIncept'21.

**Comment by utkarshxy** [comment]
@harshita9621 Sure go ahead!
