### ISSUE TITLE
spamSMSDetectionModel

### ISSUE THREAD

**Issue by hrugved06** [ZeusCodes-Official/DS-Olympus-#29]
Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**

The aim of this model is to classify whether the arrived SMS is Spam or a Ham
**Describe the solution you'd like...**

Steps which will be following:-
<ol>
  <li>Mounting the Drive</li>
  <li>Visualizing the dataset</li>
  <li>Setting-up the variables</li>
  <li>Pre-processing</li>
  <li>Then Finally, Testing </li>

</ol>

**Dataset to be used :-** Training and Testing dataset will be provided 

Please do assign the issue :-)

Thank You!

**Comment by utkarshxy** [comment]
@hrugved06 Sure go ahead! Make sure you follow the guidelines
