### ISSUE TITLE
Image/Object Segmentation Using Pixilib

### ISSUE THREAD

**Issue by Rahulraj31** [ZeusCodes-Official/DS-Olympus-#3]
Please assign me this topic. I have done Image segmentation using pixilib as well as webcam stream video segmentation also.

**Comment by utkarshxy** [comment]
Done! Go ahead. Make sure you follow the contribution guidelines. 
The folder should contain - 
✅ Jyputer Notebook (complete explanation and code to the problem)
✅ Dataset (if it is less than 100MB), Also if you have problems uploading the file or bandwidth issue, make sure you make a section about the dataset with its link in the Jyputer notebook.
✅ ReadMe - A little information about the problem and tech stack and ide used.

**Comment by utkarshxy** [comment]
Great! Thanks for contributing! 😄
