### ISSUE TITLE
Ice Cream Revenue Prediction (ML)

### ISSUE THREAD

**Issue by Manasi2001** [ZeusCodes-Official/DS-Olympus-#35]
## Aim

The aim is to predict the revenue generated by selling ice-cream on the basis of the temperature on a particular day.

## ML Algorithm to be Used

Simple Linear Regression

## Package to be Used for GUI

tkinter

**Comment by utkarshxy** [comment]
Hey @Manasi2001! 😊👋🏼
Thanks for contributing! I see you have raised multiple issues. 
Make sure you aren't making the exact same contributions for other projects and follow the guidelines provided. 
Thanks!

**Comment by Manasi2001** [comment]
> Hey @Manasi2001! 😊👋🏼
> Thanks for contributing! I see you have raised multiple issues.
> Make sure you aren't making the exact same contributions for other projects and follow the guidelines provided.
> Thanks!

Hi @utkarshxy, it's my pleasure to contribute in your amazing project! I understand your concern, but I don't think that'll be a problem. I'm tweaking my work according to the project's needs. And surely I'll follow the guidelines too. 
Good day :)
