### ISSUE TITLE
Campus Placement Prediction 

### ISSUE THREAD

**Issue by Jagannath8** [ZeusCodes-Official/DS-Olympus-#40]
**TITLE**
Campus Placement Prediction 

**DATASET**
 https://www.kaggle.com/benroshan/factors-affecting-campus-placement

**AIM**
The aim is to predict if a student is placed or not according to his/her percentage and other factors.

**APPROACH**
I'll use different ML algorithms to predict if a student is placed or not and compare accuracy between them.

Assign me this issue under DCP'21.

**Comment by Jagannath8** [comment]
Can I work on this issue?

**Comment by utkarshxy** [comment]
Sure go ahead!
