### ISSUE TITLE
Employee Retention Prediction

### ISSUE THREAD

**Issue by Jagannath8** [ZeusCodes-Official/DS-Olympus-#41]
**TITLE**
Employee Retention Prediction

**DATASET**
https://www.kaggle.com/giripujar/hr-analytics

**AIM**
The aim is to predict retention of an employee within an organization such that whether the employee will leave the company or continue with it.

**APPROACH**
I'll use different ML algorithms to predict retention of an employee and compare accuracy between them.

Assign me this issue under DCP'21.

**Comment by utkarshxy** [comment]
Assigned!
