### ISSUE TITLE
Credit Card Lead Prediction (ML)

### ISSUE THREAD

**Issue by Anjali001** [ZeusCodes-Official/DS-Olympus-#6]
Hey, I wanted to work on this dataset from Kaggle https://www.kaggle.com/sajidhussain3/jobathon-may-2021-credit-card-lead-prediction
I'll be doing the EDA and using multiple models to see which one is performing better.
Can you assign this issue to me?

**Comment by harshita9621** [comment]
Can I work on this issue .
I'll be doing EDA,Feature Selection and use different algorithm for it

**Comment by Anjali001** [comment]
> Can I work on this issue .
> I'll be doing EDA,Feature Selection and use different algorithm for it

Hello Harshita, I'm also a contributor. I opened this issue because I wanted to take it up. You can maybe search on kaggle for a different dataset and open a new issue.

**Comment by utkarshxy** [comment]
@Anjali001 You can work on it!

**Comment by utkarshxy** [comment]
> Can I work on this issue .
> I'll be doing EDA,Feature Selection and use different algorithm for it

Hey @harshita9621, I can only assign if you raise the issue. There so much that can be done. Just raise an issue and I will assign it to you!
