### ISSUE TITLE
Bitcoin Data Analysis and Price Prediction using Machine Learning.

### ISSUE THREAD

**Issue by ayushi424** [ZeusCodes-Official/DS-Olympus-#8]
Define You:

- [x] DevIncept Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
-  I want to contribute Bitcoin Data Analysis and Price Prediction using prediction algorithm in machine learning.
-  I'll perform data analysis to draw insights and understanding about the data and 
-  then perform prediction using historical data.

 
**Dataset to be used:** 
[Dataset](https://www.kaggle.com/sudalairajkumar/cryptocurrencypricehistory?select=coin_Bitcoin.csv)

Please assign it to me.

**Comment by utkarshxy** [comment]
@ayushi424 You can work on it! Make sure you are following the guidelines given in the readme.
