### ISSUE TITLE
Dogs vs Cats Image Classification

### ISSUE THREAD

**Issue by Rahulraj31** [ZeusCodes-Official/DS-Olympus-#89]

**Comment by vijay3150** [comment]
TITLE

  Dogs vs Cats image classification.

AIM 
 To classify images of cats and dogs from dataset.


Reference :

https://www.kaggle.com/chetankv/dogs-cats-images

To do :
From the given dataset we want classify the images of dogs and cats. The classification of dogs and cats by use CNN in ML.

**Comment by Rahulraj31** [comment]
> TITLE
> 
> Dogs vs Cats image classification.
> 
> AIM
> To classify images of cats and dogs from dataset.
> 
> Reference :
> 
> https://www.kaggle.com/chetankv/dogs-cats-images
> 
> To do :
> From the given dataset we want classify the images of dogs and cats. The classification of dogs and cats by use CNN in ML.
> 
> I WANT TO WORK in the ISSUE by DCP'21

bro this issue is raised by me. It is not raised by project admin.

**Comment by Rahulraj31** [comment]
@vijay3150 This is my issue so pls delete your message. So that project admin won't get confuse
