### ISSUE TITLE
CONTRIBUTION

### ISSUE THREAD

**Issue by swathi-469** [ZeusCodes-Official/DS-Olympus-#9]
I would like to add contribution guidelines for beginners in open source in a form of contribution.md file ..please assign this to me

**Comment by utkarshxy** [comment]
Sure go ahead! @swathi-469.

**Comment by swathi-469** [comment]
sure sir can you check over slack

**Comment by utkarshxy** [comment]
@lipiseth Raise a new issue. I will assign it to you.

**Comment by lipiseth** [comment]
Can you please guide me , this is my first time exploring open source through dcp21.

**Comment by utkarshxy** [comment]
Hey @lipiseth! Sure, If this is your first time with open source, I would request you to check out videos from youtube. 
Git and GitHub basics.
How to make a pull request in Github using GUI. 
How to raise an Issue on github.
